name: Deploy to Surge

on: 
  push:
    branches: 
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: 
  group: "pages"
  cancel-in-progress: true

jobs:
  buildNdeploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '20.x' # Spécifiez la version Node ici, si disponible dans les options de l'action
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Assurez-vous que Node 20.x est utilisé
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Deploy to Surge
        run: |
          npm install -g surge
          surge ./dist --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
